services:
  db:
    image: "docker.io/postgres:17-alpine"
    container_name: "listmonk_db"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "listmonk-data"
        read_only: false
    networks:
      - "aspire"
    restart: "unless-stopped"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U listmonk"
      interval: "10s"
      timeout: "5s"
      retries: 6
      start_period: "0s"
  listmonk:
    image: "listmonk/listmonk:latest"
    command:
      - "sh"
      - "-c"
      - "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"
    environment:
      LISTMONK_app__address: "0.0.0.0:9000"
      LISTMONK_db__user: "${DB_USER}"
      LISTMONK_db__password: "${DB_PASSWORD}"
      LISTMONK_db__database: "${DB_NAME}"
      LISTMONK_db__host: "listmonk_db"
      LISTMONK_db__port: "5432"
      LISTMONK_db__ssl_mode: "disable"
      LISTMONK_db__max_open: "25"
      LISTMONK_db__max_idle: "25"
      LISTMONK_db__max_lifetime: "300s"
      TZ: "Etc/UTC"
      LISTMONK_ADMIN_USER: "${LISTMONK_ADMIN_USER}"
      LISTMONK_ADMIN_PASSWORD: "${LISTMONK_ADMIN_PASSWORD}"
    ports:
      - "9000:9000"
    volumes:
      - type: "bind"
        target: "/listmonk/uploads"
        source: "D:\\repos\\blog-examples\\ListmonkAspire\\uploads"
        read_only: false
    depends_on:
      db:
        condition: "service_started"
    networks:
      - "aspire"
    restart: "unless-stopped"
networks:
  aspire:
    driver: "bridge"
volumes:
  listmonk-data:
    driver: "local"
